#!/usr/bin/env python3
"""Regenerates COVERAGE.md from the corpus itself.

The corpus is meant to grow toward even coverage of the spec, and a skew is invisible until someone
counts. This counts: what each layer holds, and how many vectors name each spec section. CI
regenerates and diffs, so the committed file cannot drift from the vectors it describes.

Stdlib only, and no TSON parser -- the `spec:` field is read by regex, which is all this needs and
keeps the repo free of a dependency on any implementation under test.
"""
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TESTS = ROOT / "tests"
OUT = ROOT / "COVERAGE.md"
SPEC_FIELD = re.compile(r'^\s*spec:\s*"([^"]*)"', re.MULTILINE)


def section_key(section: str):
    """Sorts §7.2.2 after §7.2 and before §7.3, with anything unparseable last."""
    numbers = re.findall(r"\d+", section)
    return (0, [int(n) for n in numbers]) if numbers else (1, [])


def collect():
    layers = defaultdict(Counter)
    sections = Counter()
    section_layers = defaultdict(set)
    for path in sorted(TESTS.rglob("*-expected.tn")):
        rel = path.relative_to(TESTS)
        if len(rel.parts) != 4:
            continue
        cls, layer, bucket, _ = rel.parts
        layers[(cls, layer)][bucket] += 1
        match = SPEC_FIELD.search(path.read_text(encoding="utf-8"))
        if not match:
            continue
        for section in (s.strip() for s in match.group(1).split(",")):
            sections[section] += 1
            section_layers[section].add(layer)
    return layers, sections, section_layers


def render(layers, sections, section_layers) -> str:
    total = sum(sum(c.values()) for c in layers.values())
    out = [
        "# Coverage",
        "",
        "**Generated by `scripts/coverage.py` — do not edit.** CI regenerates this file and fails on a",
        "diff, so it always describes the vectors actually present.",
        "",
        f"**{total} vectors.**",
        "",
        "## By layer",
        "",
        "| Class | Layer | valid | invalid | schema-document | total |",
        "|---|---|--:|--:|--:|--:|",
    ]
    for (cls, layer) in sorted(layers):
        c = layers[(cls, layer)]
        out.append(f"| {cls} | {layer} | {c['valid']} | {c['invalid']} | "
                   f"{c['schema-document']} | {sum(c.values())} |")
    out += [
        "",
        "## By spec section",
        "",
        "A vector naming two sections counts under both, so this column sums to more than the total.",
        "",
        "| Section | Vectors | Layers |",
        "|---|--:|---|",
    ]
    for section in sorted(sections, key=section_key):
        out.append(f"| {section} | {sections[section]} | {', '.join(sorted(section_layers[section]))} |")
    out.append("")
    return "\n".join(out)


def main() -> int:
    text = render(*collect())
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != text:
            print("COVERAGE.md is out of date -- run scripts/coverage.py and commit the result.")
            return 1
        print("OK: COVERAGE.md matches the corpus.")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
